# Site settings
title: Barebook 
siteName: Barebook
description: "Barebook is a scalable and maintainable Design System base on ITCSS architecture."
keywords:
type: website
image: /assets/images/image.jpg
url: https://barebook.gm
permalink: pretty

author: A Camariana

# Kramdown and Rouge
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge


# Global Configuration
source: src

# Sass Settings
sass:
  add_charset: true
  sass_dir: _sass
  style: :compressed

# Collections Settings
collections_dir: my_collections
collections:
  design:
    output: false
  elements:
    output: false
  components:
    output: true
  patterns:
    output: true

# Contact & Social Details